### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by weijia-cheng** [dajare/henry-james_the-portrait-of-a-lady#1]
# Semantics

- [x] Per [this page](https://archive.org/details/novelsandtalesh08unkngoog/page/n97/mode/2up), the full title of the paper referred to as the *Interviewer* seems to be *The New York Interviewer*, but in chapter-6 and chapter-13 *New York Interviewer* and *The New York Interviewer* appear with only *Interviewer* italicized.
- [x] I believe *Almanach de Gotha* should have `xml:lang="fr"`.

# CSS

- [x] I believe you need to run `pipx upgrade standardebooks` and copy the latest core.css in.

# Meta

- [x] 82dbed8550caff0d00a83bf3e16b995acbc963dc: You mixed non-editorial changes (adding an `<abbr>` semantic to “M.” in a couple of instances with the editorial changes, which you will have to rebase out. You can do `git diff -U0 --word-diff-regex=.` and search for `M\.` to find where you did this.
- [x] Another non-editorial change you mixed into the above commit was changing “The Portrait” and “The Ambassadors” to use italics in the preface. This appears in a couple of instances within that commit.
- [x] 12d56d058b7165a15238af26c6de0ba6524e2a0d: This is more of a nitpick than anything substantial, but it seems this is more like fixing a PG typo than making an editorial change. It was already transcribed wrong so I would personally have considered this a non-editorial typo fix. (I would have considered it editorial if the PG text had used the ligature.)

**Comment by dajare** [comment]
> You still have an instance of `New York <i epub:type="se:name.publication.newspaper">Interviewer</i>` (see chapter-13).

Hi @weijia-cheng!   
Right - I know. :) I've been researching how to rebase that `82dbed8` commit - non-trivial for me (I'm just on the point of attempting that now), then my daughter got home and we went for a walk! I pushed those commits just in case I messed up my local repo. :grimacing: Here's the comment that was still in draft

- **Semantics** - good catch! It works for ch. 6 (that you linked), but [not for ch. 13](https://archive.org/details/novelsandtalesh08unkngoog/page/n195/mode/1up?view=theater) where only _Interviewer_ is in italics (and `the` lowercase `t`), so I've left that one.

It seems to me if you want the ch. 13 one to look like ch. 6, it means an \[Editorial\] commit - or do you see something I'm missing?

**Comment by weijia-cheng** [comment]
Oh, I just meant that “New York” in “New York Interviewer” should be italicized too.

**Comment by dajare** [comment]
> Oh, I just meant that “New York” in “New York Interviewer” should be italicized too.

I thought that's what you meant — but that's [not what the text has](https://archive.org/details/novelsandtalesh08unkngoog/page/n195/mode/1up?view=theater)! So if you want that in Italics, that seems "Editorial", right? That would be somewhat like the case you want me to change for the Preface.... :man_shrugging:

**Comment by dajare** [comment]
Oh wait - I think I'm mis-reading that middle message. You DO want those quote-to-italics in the Preface to be non-Editorial! Sorry! I must need more coffee.... (Still heavily jet-lagged after returning to Scotland from two months in Indonesia!) I'm on it. I'll be pushing the revised repo soon.....

**Comment by dajare** [comment]
Latest: I managed the `<abbr>M.</abbr>` rebase (the first one) without difficult. Now struggling to get the Preface in shape: I'm getting conflicts with later commits, so I'm obviously getting something wrong. Will persevere......

**Comment by dajare** [comment]
Okay, @weijia-cheng - I think I managed it (except for ch. 13). Let me know if that's right! I live in hope.....

**Comment by dajare** [comment]
P.s. I re-read the "long description" and realized it contained a phrase surplus to requirements, so I took it out > a742747. I hope that's OK! Thanks, again @weijia-cheng
